version: '3.4'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7023:8080"
    networks:
      - backend-network
    environment:

      # JWT Issuer
      - JWT_ISSUER=ltdedtn


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - backend-network

networks:
  backend-network:
