USE [master]
GO
/****** Object:  Database [Phase 2]    Script Date: 19/08/2024 4:09:19 pm ******/
CREATE DATABASE [Phase 2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Phase 2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER01\MSSQL\DATA\Phase 2.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Phase 2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER01\MSSQL\DATA\Phase 2_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Phase 2] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Phase 2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Phase 2] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Phase 2] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Phase 2] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Phase 2] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Phase 2] SET ARITHABORT OFF 
GO
ALTER DATABASE [Phase 2] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Phase 2] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Phase 2] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Phase 2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Phase 2] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Phase 2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Phase 2] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Phase 2] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Phase 2] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Phase 2] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Phase 2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Phase 2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Phase 2] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Phase 2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Phase 2] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Phase 2] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Phase 2] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Phase 2] SET RECOVERY FULL 
GO
ALTER DATABASE [Phase 2] SET  MULTI_USER 
GO
ALTER DATABASE [Phase 2] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Phase 2] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Phase 2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Phase 2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Phase 2] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Phase 2] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Phase 2', N'ON'
GO
ALTER DATABASE [Phase 2] SET QUERY_STORE = ON
GO
ALTER DATABASE [Phase 2] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Phase 2]
GO
/****** Object:  User [Ben]    Script Date: 19/08/2024 4:09:20 pm ******/
CREATE USER [Ben] FOR LOGIN [Ben] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [Ben]
GO
ALTER ROLE [db_accessadmin] ADD MEMBER [Ben]
GO
ALTER ROLE [db_securityadmin] ADD MEMBER [Ben]
GO
ALTER ROLE [db_ddladmin] ADD MEMBER [Ben]
GO
ALTER ROLE [db_backupoperator] ADD MEMBER [Ben]
GO
ALTER ROLE [db_datareader] ADD MEMBER [Ben]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [Ben]
GO
ALTER ROLE [db_denydatareader] ADD MEMBER [Ben]
GO
ALTER ROLE [db_denydatawriter] ADD MEMBER [Ben]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 19/08/2024 4:09:20 pm ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Characters]    Script Date: 19/08/2024 4:09:20 pm ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Characters](
	[CharacterId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Description] [nvarchar](max) NULL,
	[StoryId] [int] NULL,
	[ImageUrl] [nvarchar](max) NULL,
	[RelationshipStatus] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CharacterId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Roles]    Script Date: 19/08/2024 4:09:20 pm ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Roles](
	[RoleId] [int] IDENTITY(1,1) NOT NULL,
	[RoleName] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RoleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Stories]    Script Date: 19/08/2024 4:09:20 pm ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Stories](
	[StoryId] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](100) NOT NULL,
	[Description] [nvarchar](max) NULL,
	[CreatedAt] [datetime] NULL,
	[UserId] [int] NULL,
	[ImageUrl] [nvarchar](max) NULL,
	[Content] [varchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[StoryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[StoryPartCharacters]    Script Date: 19/08/2024 4:09:20 pm ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[StoryPartCharacters](
	[StoryPartId] [int] NOT NULL,
	[CharacterId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[StoryPartId] ASC,
	[CharacterId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[StoryParts]    Script Date: 19/08/2024 4:09:20 pm ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[StoryParts](
	[PartId] [int] IDENTITY(1,1) NOT NULL,
	[Content] [nvarchar](max) NOT NULL,
	[StoryId] [int] NULL,
	[CreatedAt] [datetime2](7) NULL,
	[ImageUrl] [nvarchar](max) NULL,
	[Description] [varchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[PartId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserRoles]    Script Date: 19/08/2024 4:09:20 pm ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserRoles](
	[UserId] [int] NOT NULL,
	[RoleId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UserId] ASC,
	[RoleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 19/08/2024 4:09:20 pm ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserId] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](50) NOT NULL,
	[PasswordHash] [nvarchar](256) NOT NULL,
	[Email] [nvarchar](100) NOT NULL,
	[CreatedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [idx_StoryId]    Script Date: 19/08/2024 4:09:20 pm ******/
CREATE NONCLUSTERED INDEX [idx_StoryId] ON [dbo].[Characters]
(
	[StoryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [idx_StoryId_CharacterId]    Script Date: 19/08/2024 4:09:20 pm ******/
CREATE NONCLUSTERED INDEX [idx_StoryId_CharacterId] ON [dbo].[StoryPartCharacters]
(
	[StoryPartId] ASC,
	[CharacterId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Characters] ADD  DEFAULT ('neutral') FOR [RelationshipStatus]
GO
ALTER TABLE [dbo].[Stories] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[StoryParts] ADD  CONSTRAINT [DF_StoryParts_CreatedAt]  DEFAULT (getdate()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[Users] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[Characters]  WITH CHECK ADD FOREIGN KEY([StoryId])
REFERENCES [dbo].[Stories] ([StoryId])
GO
ALTER TABLE [dbo].[Stories]  WITH CHECK ADD FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[StoryPartCharacters]  WITH CHECK ADD FOREIGN KEY([CharacterId])
REFERENCES [dbo].[Characters] ([CharacterId])
GO
ALTER TABLE [dbo].[StoryPartCharacters]  WITH CHECK ADD FOREIGN KEY([StoryPartId])
REFERENCES [dbo].[StoryParts] ([PartId])
GO
ALTER TABLE [dbo].[StoryParts]  WITH CHECK ADD FOREIGN KEY([StoryId])
REFERENCES [dbo].[Stories] ([StoryId])
GO
ALTER TABLE [dbo].[UserRoles]  WITH CHECK ADD FOREIGN KEY([RoleId])
REFERENCES [dbo].[Roles] ([RoleId])
GO
ALTER TABLE [dbo].[UserRoles]  WITH CHECK ADD FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([UserId])
GO
USE [master]
GO
ALTER DATABASE [Phase 2] SET  READ_WRITE 
GO
